name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ModusToolbox 3.4
        run: |
          wget -q https://softwaretoolshosting.infineon.com/packages/com.ifx.tb.tool.modustoolboxsetup/versions/1.2.0.787/artifacts/ModusToolboxSetupInstaller_1.2.0.787_linux_x64.deb/download -O modustoolbox.deb
          sudo dpkg -i modustoolbox.deb || sudo apt-get -f install -y

      - name: Set environment variables
        run: echo "PATH=$HOME/ModusToolbox/tools_3.4:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build gcc-arm-none-eabi

      - name: Get PSoC6 libraries
        working-directory: Firmware/BlinkLED
        run: make getlibs

      - name: Build firmware
        working-directory: Firmware/BlinkLED
        run: make build

      - name: Upload compiled firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: Firmware/BlinkLED/build/*.hex
