name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ModusToolbox
        run: |
          Start-Process -Wait -FilePath .\Artifacts\ModusToolboxSetup.exe -ArgumentList "/S" -NoNewWindow -PassThru
          Write-Output "ModusToolbox installation complete"

      - name: Install dependencies
        run: |
          choco install cmake ninja -y
          choco install gcc-arm-embedded -y

      - name: Get PSoC6 libraries
        working-directory: Firmware/BlinkLED
        run: make getlibs

      - name: Build firmware
        working-directory: Firmware/BlinkLED
        run: make build

      - name: Upload compiled firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: Firmware/BlinkLED\build\*.hex